### ISSUE TITLE
kanban board setup

### ISSUE THREAD

**Issue by tonnytech** [addisalemseifu/Recipe-App#2]
project link: https://github.com/addisalemseifu/Recipe-App/projects?query=is%3Aopen

This is a group of two people

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Team work ✔️ 
- Correct GitFlow ✔️ 
- Good implementations ✔️

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! Please fix your all `tasks` you created in your `Kanban` because they should be created like required one by `Microverse`. When you click to any tasks, task should opened as pop-up window and showed task's description and team members assigned as `single` and `team`. Lastly, each created tasks should have their own `issues` and issue automatic generated when you create your task. Please implement my suggestions 🙏🏼 

![image](https://github.com/addisalemseifu/Recipe-App/assets/63915024/fe326178-da79-4474-8c1b-70d5b0eb3ee0)


## Optional suggestions
- [ ] [OPTIONAL] It would be logical and proffessional if you give correct name to your `Repository` 👍🏼 

![image](https://github.com/addisalemseifu/Recipe-App/assets/63915024/c8565619-516b-4616-ad9e-585e838363f3)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
